# Generated by Django 5.1.4 on 2025-01-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="foto"
            ),
        ),
    ]
